# Generated by Django 4.0.1 on 2022-01-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_opz_16_options_alter_opz_26_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPZ_26',
            new_name='Course1',
        ),
        migrations.RenameModel(
            old_name='OPZ_16',
            new_name='Course2',
        ),
        migrations.RenameModel(
            old_name='OPZ_36',
            new_name='Course3',
        ),
    ]
