# Generated by Django 4.0.1 on 2022-02-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rename_opz_26_course1_rename_opz_16_course2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='group')),
                ('lessons', models.TextField(default='lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='group')),
                ('lessons', models.TextField(default='lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='group')),
                ('lessons', models.TextField(default='lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='group')),
                ('lessons', models.TextField(default='lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='group')),
                ('lessons', models.TextField(default='lessons')),
            ],
        ),
        migrations.DeleteModel(
            name='Course1',
        ),
        migrations.DeleteModel(
            name='Course2',
        ),
        migrations.DeleteModel(
            name='Course3',
        ),
    ]
