# Generated by Django 4.0.1 on 2022-01-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPZ_16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('мonday', models.TextField()),
                ('tuesday', models.TextField()),
                ('wednesday', models.TextField()),
                ('thursday', models.TextField()),
                ('friday', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OPZ_26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('мonday', models.TextField()),
                ('tuesday', models.TextField()),
                ('wednesday', models.TextField()),
                ('thursday', models.TextField()),
                ('friday', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OPZ_36',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('мonday', models.TextField()),
                ('tuesday', models.TextField()),
                ('wednesday', models.TextField()),
                ('thursday', models.TextField()),
                ('friday', models.TextField()),
            ],
        ),
    ]
