# Generated by Django 4.0.1 on 2022-01-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opz_16',
            options={'verbose_name': 'OPZ-16'},
        ),
    ]
