# Generated by Django 4.0.1 on 2022-01-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_opz_16_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opz_16',
            options={'verbose_name': 'OPZ-16', 'verbose_name_plural': 'OPZ-16'},
        ),
        migrations.AlterModelOptions(
            name='opz_26',
            options={'verbose_name': 'OPZ-26', 'verbose_name_plural': 'OPZ-26'},
        ),
        migrations.AlterModelOptions(
            name='opz_36',
            options={'verbose_name': 'OPZ-36', 'verbose_name_plural': 'OPZ-36'},
        ),
    ]
