# Generated by Django 4.0.1 on 2022-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_opz_16_options_alter_opz_26_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opz_16',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opz_26',
            options={},
        ),
        migrations.AlterModelOptions(
            name='opz_36',
            options={},
        ),
        migrations.AddField(
            model_name='opz_16',
            name='group',
            field=models.TextField(default='ddd'),
        ),
        migrations.AddField(
            model_name='opz_26',
            name='group',
            field=models.TextField(default='ddd'),
        ),
        migrations.AddField(
            model_name='opz_36',
            name='group',
            field=models.TextField(default='ddd'),
        ),
    ]
