# Generated by Django 4.0.1 on 2022-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
